urls.py
from django.conf.urls.defaults import patterns, include, url

from django.views.generic import ListView, DetailView
from django.views.generic.simple import direct_to_template

from interface.models import Team, Player, Emailer

from django.contrib import admin
admin.autodiscover()

teamDetail = DetailView.as_view(model=Team, template_name= "teamDetail.html")
emailerDetail = DetailView.as_view(model=Emailer, template_name= "emailerDetail.html")

emailerList = ListView.as_view(model=Emailer, template_name= "emailerList.html")
# teamList = ListView.as_view(model=Team, template_name= "teamList.html")


urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'interface.views.home', name='home'),
    url(r'^team/(?P<pk>[a-z\d]+)/$', teamDetail, name='teamDetail'),
    url(r'^emailers/$', emailerList, name='emailerList'),
    url(r'^teams/$', 'interface.views.teamList', name='teamList'),
    url(r'^emailer/(?P<pk>[a-z\d]+)/$', emailerDetail, name='emailerDetail'),

    url(r'^help/$', direct_to_template, {'template': 'help.html'}),

    url(r'^edit/?$', 'interface.views.editTeam', name='editTeam'),
    url(r'^remove/?(?P<id>[a-z\d]+)/$', 'interface.views.removePlayer'),
    url(r'^add/?(?P<id>[a-z\d]+)/$', 'interface.views.addPlayer'),

    (r'^accounts/profile/.*', 'interface.views.home'),
    (r'^users/.*', 'interface.views.home'),
    (r'^accounts/', include('registration.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

interface/models.py
from django.db import models
# from autoslug import AutoSlugField

from django.db.models.signals import post_save
from django.contrib.auth.models import User

from django.dispatch import dispatcher



class Emailer(models.Model):
	name = models.CharField(max_length=200)
	netId = models.CharField(max_length=200)
	image = models.CharField(max_length=200)
	user = models.ForeignKey(User, null=True, blank=True)
        # slug = AutoSlugField(populate_from='name')
	def __str__(self):
		return self.name
        class Meta:
            ordering= ["name"]

class EmailAddress(models.Model):
	emailer = models.ForeignKey(Emailer)
	emailAddress = models.CharField(max_length=200)
	realEmail = models.CharField(max_length=200, blank=True)
	def __str__(self):
		return "%s: %s" % (self.emailer.name, self.emailAddress)
 
# class User(models.Model):
# 	name = models.CharField(max_length=200)
# 	email = models.CharField(max_length=200)
# 	image = models.CharField(max_length=200)
# 	def __str__(self): return self.name

class Team(models.Model):
	name = models.CharField(max_length=200)
	user = models.ForeignKey(User)
        # slug = AutoSlugField(populate_from='name')
        def __str__(self):
		return "%s: %s" % (self.user, self.name)
        def getTotalScore(self):
            for score in  self.teamscore_set.all():
                if score.total == True:
                    return score.score

class Player(models.Model):
	team = models.ForeignKey(Team)
	emailer = models.ForeignKey(Emailer)
	points = models.IntegerField()
	def __str__(self): return "%s" % self.team
        def name(self):
            return self.emailer.name

class PlayerTransaction(models.Model):
	timestamp = models.DateTimeField()
	team = models.ForeignKey(Team)
	emailer = models.ForeignKey(Emailer)
	points = models.IntegerField() # allocation, 0 is remove, 1 is one of them, 2 is two, etc
	def __str__(self): return "%s set %s to %d at %s" % (self.team.name, self.emailer.name, self.points, self.timestamp)
        def name(self):
            return self.emailer.name

class Category(models.Model):
	name = models.CharField(max_length=200)
	total = models.BooleanField()
	description = models.TextField()
	def __str__(self): return self.name

class EmailerPoints(models.Model):
	emailer = models.ForeignKey(Emailer)
	category = models.ForeignKey(Category)
	points = models.IntegerField()
	total = models.BooleanField()
	def __str__(self): return "[%s] %s: %s" % (self.category, self.emailer, self.points)

class TeamPoints(models.Model):
	team = models.ForeignKey(Team)
	category = models.ForeignKey(Category)
	points = models.IntegerField()
	total = models.BooleanField()
	def __str__(self): return "[%s] %s: %s" % (self.category, self.team, self.points)

class TeamScore(models.Model):
	team = models.ForeignKey(Team)
	category = models.ForeignKey(Category)
	score = models.IntegerField()
	total = models.BooleanField()
	def __str__(self): return "[%s] %s: %s" % (self.category, self.team, self.score)



def createNewTeam(sender, created, instance=None, **kwargs):
    if instance is None:
        return
    if created == True:
        name = instance.username + "'s Team"
        new_team, was_created= Team.objects.get_or_create(name =name, user=instance)
        if was_created: # silly, but there seems to be a bug in the created var coming from the signal
            print instance.email
            # doh regex needs to applied on EmailAdress model, not our user instance
            matching_email_address= EmailAddress.objects.filter(realEmail= instance.email)
            if len(matching_email_address):
                print 'email matched'
                emailer= matching_email_address[0].emailer
                emailer.user = instance
                emailer.save()



post_save.connect(createNewTeam, sender=User)

templates/base.html
<head>
  <title> RiskyListy!</title>
  <link rel="stylesheet" href="{{STATIC_URL}}bootstrap/css/bootstrap.css" media="screen" />
  <link rel="stylesheet" href="{{STATIC_URL}}ourstyle.css" media="screen" />
</head>

<body>
  <div class="navbar ">
      <div class="navbar-inner">
            <div class="container">
              <a class="brand" href="/">
                <img src="{{STATIC_URL}}img/logo.gif" alt="RiskyListy" />
                 </a>
             <ul class="nav pull-right">
               <li> <a href="/help/">Rules/Help </a></li>
               {%if not user.is_authenticated %}
               <li> <a href="/accounts/login/">Login </a></li>
               <li> <a href="/accounts/register/">Register </a></li>
               {% else %} 
               <li> <a href="/edit">Your Team </a></li>
               <li> <a href="/teams"> Other Teams </a></li>
               <li> <a href="/emailers"> List All Emailers </a></li>
               {% endif %}
             <ul>
                   
            </div>
        </div>
  </div>
  <br>
  <div class="container">
    {% block content %}
    {%endblock %}
  </div> {#end container #}
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30195395-1']);
  _gaq.push(['_setDomainName', 'boxysean.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>

templates/editTeam.html
{% extends 'base.html' %}

{% block content %}
  <h1>Manage {{team.name}}</h1>
  <br>
  <h3> Players On This Team </h3>
  <ul>

    {%if team.player_set.all|length > 0 %}
  {% for player in team.player_set.all %}
  <li> <a href="/emailer/{{player.emailer.id}}">{{player.name}} </a>  
      <ul>
        {% for  rank in  player.emailer.emailerpointranking_set.all %} 
        <li> {{rank.category}}= {{rank.points}} points </li>
         {%endfor%}
      </ul>
    </li>
  {%endfor %}
  </ul>
  <h3> Team Points <small> By Category</small> </h3>
  <ul>
    {# this is no longer actually ranking but w/e #}
  {% for ranking in team.teampoints_set.all %}
    <li> {{ranking.category}} : {{ranking.points}} </li>
  {%endfor%}
  </ul>
  <h3> Total Score </h3>
  <ul>
    {% for tscore in team.teamscore_set.all %}
    {% if forloop.last %}
    <li class="strong total"> Grand {{tscore.category}}: {{tscore.score}} </li>
    {% else %}
    <li> {{tscore.category}}: {{tscore.score}} </li>
    {% endif %}
    {%endfor %}
    </ul>
  <br><br><br>

  <h3> Kick Players Off Your Team</h3>
  {% for player in team_players %}
  <a href="/emailer/{{player.emailer.id}}">{{player.name}} </a>  <a class="btn btn-small  btn-danger" href="/remove/{{player.id}}"> Cut this player </a>
  <br>
  <br>
  {%endfor%}

  <br>
    <a class="btn btn-success btn-large"  href="/emailers/"> Recruit other  emailers.</a>
    {%else%} {# end of player length #}
  <p> None. Why don't you add some</p>
    <a class="btn btn-success btn-large"  href="/emailers/"> Add  players.</a>
    {%endif%}
    <br><br>
    <br><br>
{% endblock %}

templates/emailerDetail.html
{% extends 'base.html' %}
{%block content %}
  <h1> {{object}} </h1>
  <br>
  <h3> Emailer Stats Since March 1 </h3> 
  {% for epoints in object.emailerpoints_set.all%}
 
  <li> {{epoints.category}}: {{epoints.points}} <i> points</i></li> 
  
  {%endfor %}
  
  <br>
  <a class="btn btn-primary"  href="/add/{{object.id}}"> Recruit this Emailer</a> to play for your team.
{%endblock%}

templates/emailerList.html
{% extends 'base.html' %}
{%block content %}
  <h1> Roster of Emailers </h1>
  {% for emailer in object_list %}
  <p>
  <a href="/emailer/{{emailer.id}}">{{emailer}}</a>
  </p>
  {%endfor%}
  

{%endblock%}

templates/error.html
{% extends 'base.html' %}

{% block content %}
<br><br><br>
<h1> {{headline}} </h1>
<br>
<h2> {{message}} </h2>
<p> </p>
<p> <a href="/"> Go back</a>
{% endblock %}

templates/help.html
{% extends 'base.html' %}

{% block content %}
<br>
<h1> Rules, Help, &amp; FAQ </h1>
<br><br>
<h2>FAQ</h2>

<h3>What is RiskyListy?</h3>

<p>RiskyListy is a <a href="http://en.wikipedia.org/wiki/Fantasy_sport">fantasy sports</a> inspired game for the ITP mailing list. You, as a team manager in the game, own players who are your fellow classmates and emailers on the list. The players earn you points for categories defined in RiskyListy.</p>

<p>For example, if your player sends an email with the words "Thank you" in the subject line and is not a reply to another email, then your player will earn you 1 point for the Thank You category. The categories are described further below.</p>

<h3>Fantasy sports, you say?</h3>

See this nice <a href="http://entertainment.howstuffworks.com/fantasy-football1.htm">overview of fantasy football</a> for a better idea.

<h3>How does points, scoring, and ranking work?</h3>

<p>Each player on your team earns you <strong>points</strong> for each of the game categories (defined below). Your <strong>team points</strong> is the sum of all the points your players have earned for you in each category. There are 5 categories, so you have 5 types of team points.</p>

<p>Your ranking is determined by your <strong>total score</strong>. Total score is the sum of each <strong>score</strong> per category. Your points determine your score: the person with the most points in a category gets the highest score for that category. The person with the second most points in a category gets the second highest score, etc. In particular, if there are N players and you have the most points in a category, you get a score of N. The second highest point-getter in that category gets a score of N-1, and so on.</p>

<p>Teams that have 0 points for a category get a score of 0 for that category. Teams that have the same number of points for a category get the same score.</p>

{# <p>Tiebreakers: If two teams have the same total score, then the team with the higher total points is ranked higher. If two teams also have the same total points, then they are ranked based on their first name and then last name.</p> #}

<p class="total"> <strong>TLDR:</strong> Pick the players (aka emailers) that you think will do the best in each of the categories. <br> The more competitive a category is, the higher your score.</p> 

<h3>Are points cumulative?</h3>

<p>Yes, points will be gained over the length of the game and will not disappear or be compounded.</p>

<h3>How many players can I have on my team at once?</h3>

<p>8</p>

<h3>How many times can I add and drop players?</h3>

<p>As many times as you'd like.</p>

<h3>When do changes to my team lineup take effect?</h3>

<p>Immediately.</p>

<h3>Can two or more teams own the same player?</h3>

<p>Yes.</p>

<h3>Can I have two or more of the same players on my team?</h3>

<p>No.</p>

<h3>Can I be an player on my own team?</h3>

<p>No.</p>

<h3>If I add a player to my team, do I get the points they earned in the past?</h3>

<p>No, you only receive points for the player when the player is on your team.</p>

<h3>How often is the website updated?</h3>

<p>Approximately every 15 minutes.</p>

<br><br>
<h2>Categories</h2>

<h3>Thank You</h3>

<p>Gives a point for an email whose subject line contains either "thanks" or "thank you" (case-insensitive). Replies to or forwards of such emails do not count.</p>

<h3>Free Food</h3>

<p>Gives a point for an email whose subject line or body contains "free food" (case-insensitive). Replies to or forwards of such emails do not count.</p>

<h3>GIFs</h3>

<p>Gives a point for an email whose body contains a link to a GIF file, has a GIF file attached, or has a GIF file in the body of the email. Replies to or forwards of such emails do not count.</p>

<h3>Conversation Starter</h3>

<p>Awards X points to an email that receives X replies. For example, if Johnny sends an email and Jane replies to Johnny's email, then Johnny gets 1 point for the teams that have selected Johnny.</p>

<h3>Praise The Creators</h3>

<p>Gives a point for emails whose subject line contains the phrase "you are the best, ______" where the blank is one of Naliaka, Sheiva, Sean, Tiffany, or Zach. (Case-insensitive.) Replies or forwards do not count.</p>

<br><br>
<h2>Help</h2>

<p>If you have any questions or find any bugs, send an email or talk to one of Sean, Zach, Naliaka, Tiffany, or Sheiva.</p>

<br><br>
<br><br>
{% endblock %}

templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1> Welcome to RiskyListy! </h1>
<h2> The game of risk on the list, or something clever about fantasies</h2>
    <br><br>
    <a href="/accounts/register"> Create Your account! </a>
    <br>
    <a href="/accounts/login"> Log in!  </a>
    
    {# <a href="/emailers/"> See a list of all available players</a> #}

    {% endblock %}

templates/teamDetail.html
{% extends 'base.html' %}

{% block content %}

  <h1>{{object.name}}</h1>
  <br>
  <h3> Players On This  Team </h3>
  <ul>

  {% for player in object.player_set.all %}
    <li> {{player.name}} </li>
  {%endfor %}
  </ul>


  <h3> Team Points <small> By Category</small> </h3>
  <ul>
  {% for ranking in object.teampoints_set.all %}
    <li> {{ranking.category}} : {{ranking.points}} </li>
  {%endfor%}
  </ul>
  <h3> Total Score </h3>
  <ul>
    {% for tscore in object.teamscore_set.all %}
    {% if forloop.last %}
    <li class="strong total"> Grand {{tscore.category}}: {{tscore.score}} </li>
    {% else %}
    <li> {{tscore.category}}: {{tscore.score}} </li>
    {% endif %}
    {%endfor %}
    </ul>
  <br><br><br>







{% endblock %}

templates/teamList.html
{% extends 'base.html' %}
{%block content %}
  <h1> Your Rival Teams </h1>
  <table class="table table-striped">
    <thead>
      <th>Team</th>
      <th> Gifs </th>
      <th> Free Food </th>
      <th> Convo Starter </th>
      <th> Praise Creators </th>
      <th> Thankyou</th>
      <th class="strong"> Total Score</th>

    </thead>
  {% for team in object_list %}
  <tr>
    <td><a href="/team/{{team.id}}">{{team.name}}</a></td>
    {# <td> {{team.getTotalScore}}<td> #}
    {% for tscore in team.teamscore_set.all %}
     {% if forloop.last %}
      <td class="strong"> {{tscore.score}}</td>
     {% else%}
      <td> {{tscore.score}}</td>
     {% endif%}
    {% endfor%}
  </tr>
  {%endfor%}
  </table>

{%endblock%}